# Hannah Malak
# 07/19/21
# Exercise 15 - Building Tesselations

```{r, message = FALSE, warning = FALSE}

library(tidyverse)
library(dplyr)
library(sf)
library(USAboundaries)
library(knitr)
library(gghighlight)

# Step 1.1

CONUS = USAboundaries::us_counties() %>% 
  filter(!state_name %in% c("Alaska", "Hawaii", "Puerto Rico")) %>% 
  st_transform(5070)

# Step 1.2

centroids = CONUS %>% 
  st_centroid() %>% 
  st_combine() %>% 
  st_cast("MULTIPOINT")

# Step 1.3

voronoi = st_voronoi(centroids) %>% 
  st_cast() %>% 
  st_as_sf() %>% 
  mutate(id = 1:n())

triangulated = st_triangulate(centroids) %>% 
  st_cast() %>% 
  st_as_sf() %>% 
  mutate(id = 1:n())

gridded = st_make_grid(CONUS, n = 70) %>% 
  st_cast() %>% 
  st_as_sf() %>% 
  mutate(id = 1:n())

hex = st_make_grid(CONUS, n = (70), square = FALSE) %>% 
  st_cast %>% 
  st_as_sf() %>% 
  mutate(id = 1:n())

# Step 1.4

CONUS_union = us_counties() %>% 
  filter(!state_name %in% c("Alaska", "Hawaii", "Puerto Rico")) %>% 
  st_transform(5070) %>% 
  st_union()

# Step 1.5

CONUS_union_simple = CONUS_union %>% 
  rmapshaper::ms_simplify(keep = 0.1)

mapview::npts(CONUS_union)
mapview::npts(CONUS_union_simple)

```

#### By using the ms_simplify function to simplify the geometry, I reduced the amount of points from 3229 to 322. This means that the geometry is less complex, but a less complex geometry means that computations will be faster.

```{r, message = FALSE, warning = FALSE}

# Step 1.5

voronoi_crop = st_intersection(voronoi, CONUS_union_simple)

triangulated_crop = st_intersection(triangulated, CONUS_union_simple)

# Step 1.6

tessellation_plot = function(data, title){
  ggplot() +
    geom_sf(data = data, fill = "white", col = "navy", size = .2) +
    theme_void() +
    labs(title = title,
         caption = paste("There are", nrow(data), "tiles in this tessellation."))
}

# Step 1.7

tessellation_plot(CONUS, "Original Counties")

tessellation_plot(voronoi_crop, "Voronoi")

tessellation_plot(triangulated_crop, "Triangulated")

tessellation_plot(gridded, "Square")

tessellation_plot(hex, "Hexagonal")

```

